ITEMS = [
    # Active bids
    {"id": 1, "lot": "LOT-4821", "title": "Apple MacBook Pro 14\" M3 2023", "description": "Slight wear on keyboard, charger included, 16GB RAM 512GB SSD", "category": "Electronics", "retail_price": 1999.00, "current_bid": 612.00, "my_bid": 650.00, "condition": "Good", "status": "active", "pickup_status": None, "pickup_date": None, "location": "Row C, Shelf 4", "row": "C", "position": 4, "auction_end": "2026-04-30T18:00:00"},
    {"id": 2, "lot": "LOT-5033", "title": "Dyson V15 Detect Cordless Vacuum", "description": "Complete with all attachments, runs perfectly, no filters needed", "category": "Appliances", "retail_price": 749.99, "current_bid": 180.00, "my_bid": 200.00, "condition": "Like New", "status": "active", "pickup_status": None, "pickup_date": None, "location": "Row B, Shelf 1", "row": "B", "position": 1, "auction_end": "2026-04-30T20:00:00"},
    {"id": 3, "lot": "LOT-5210", "title": "Sony PlayStation 5 Console Bundle", "description": "Disc edition, 2 controllers, 3 games included, all cables", "category": "Gaming", "retail_price": 499.99, "current_bid": 221.00, "my_bid": 240.00, "condition": "Good", "status": "active", "pickup_status": None, "pickup_date": None, "location": "Row A, Shelf 6", "row": "A", "position": 6, "auction_end": "2026-05-01T14:00:00"},
    {"id": 4, "lot": "LOT-5388", "title": "Weber Genesis E-325s Gas Grill", "description": "3-burner propane grill, minor rust on grates, cover included", "category": "Outdoor", "retail_price": 899.00, "current_bid": 195.00, "my_bid": 220.00, "condition": "Fair", "status": "active", "pickup_status": None, "pickup_date": None, "location": "Row D, Shelf 2", "row": "D", "position": 2, "auction_end": "2026-05-01T16:00:00"},
    {"id": 5, "lot": "LOT-5441", "title": "DeWalt 20V MAX Power Tool Combo Kit", "description": "Drill, circular saw, jigsaw, 2 batteries and charger included", "category": "Tools", "retail_price": 449.00, "current_bid": 98.00, "my_bid": 115.00, "condition": "Good", "status": "active", "pickup_status": None, "pickup_date": None, "location": "Row B, Shelf 3", "row": "B", "position": 3, "auction_end": "2026-05-02T12:00:00"},

    # Won — pending pickup
    {"id": 6, "lot": "LOT-4190", "title": "Samsung 65\" QLED 4K Smart TV", "description": "2023 model, remote included, minor scratches on bezel", "category": "Electronics", "retail_price": 1299.99, "current_bid": 287.00, "my_bid": 287.00, "condition": "Good", "status": "won", "pickup_status": "pending", "pickup_date": "2026-04-28", "location": "Row A, Shelf 2", "row": "A", "position": 2, "auction_end": "2026-04-24T18:00:00"},
    {"id": 7, "lot": "LOT-4312", "title": "KitchenAid Artisan Stand Mixer 5qt", "description": "Empire Red, all original attachments, works perfectly", "category": "Appliances", "retail_price": 499.95, "current_bid": 112.00, "my_bid": 112.00, "condition": "Like New", "status": "won", "pickup_status": "pending", "pickup_date": "2026-04-28", "location": "Row B, Shelf 5", "row": "B", "position": 5, "auction_end": "2026-04-24T20:00:00"},
    {"id": 8, "lot": "LOT-4455", "title": "Trek Marlin 5 Mountain Bike 2022", "description": "29\" wheels, medium frame, few minor scratches, tires good condition", "category": "Sports", "retail_price": 679.99, "current_bid": 201.00, "my_bid": 201.00, "condition": "Good", "status": "won", "pickup_status": "scheduled", "pickup_date": "2026-04-28", "location": "Row C, Shelf 1", "row": "C", "position": 1, "auction_end": "2026-04-24T16:00:00"},
    {"id": 9, "lot": "LOT-4601", "title": "Bose QuietComfort 45 Headphones", "description": "Wireless noise cancelling, case and cables included, like new", "category": "Electronics", "retail_price": 329.00, "current_bid": 88.00, "my_bid": 88.00, "condition": "Like New", "status": "won", "pickup_status": "pending", "pickup_date": "2026-04-29", "location": "Row A, Shelf 3", "row": "A", "position": 3, "auction_end": "2026-04-23T18:00:00"},
    {"id": 10, "lot": "LOT-4720", "title": "iRobot Roomba j7+ Robot Vacuum", "description": "Self-emptying base included, works great, minor cosmetic wear", "category": "Appliances", "retail_price": 799.99, "current_bid": 143.00, "my_bid": 143.00, "condition": "Good", "status": "won", "pickup_status": "pending", "pickup_date": "2026-04-29", "location": "Row B, Shelf 2", "row": "B", "position": 2, "auction_end": "2026-04-23T20:00:00"},
    {"id": 11, "lot": "LOT-4815", "title": "Traeger Pro 575 Wood Pellet Grill", "description": "WiFIRE enabled, cover included, slight grease stains inside", "category": "Outdoor", "retail_price": 799.99, "current_bid": 265.00, "my_bid": 265.00, "condition": "Good", "status": "won", "pickup_status": "scheduled", "pickup_date": "2026-04-28", "location": "Row D, Shelf 1", "row": "D", "position": 1, "auction_end": "2026-04-23T14:00:00"},

    # Picked up
    {"id": 12, "lot": "LOT-3901", "title": "LG 27\" 4K UHD Monitor", "description": "USB-C, HDR10, all cables included, no dead pixels", "category": "Electronics", "retail_price": 449.99, "current_bid": 97.00, "my_bid": 97.00, "condition": "Good", "status": "picked_up", "pickup_status": "completed", "pickup_date": "2026-04-20", "location": "Row A, Shelf 1", "row": "A", "position": 1, "auction_end": "2026-04-18T18:00:00"},
    {"id": 13, "lot": "LOT-3975", "title": "Instant Pot Duo 8qt Pressure Cooker", "description": "All accessories included, used twice, like new condition", "category": "Appliances", "retail_price": 129.99, "current_bid": 28.00, "my_bid": 28.00, "condition": "Like New", "status": "picked_up", "pickup_status": "completed", "pickup_date": "2026-04-20", "location": "Row B, Shelf 4", "row": "B", "position": 4, "auction_end": "2026-04-18T20:00:00"},
    {"id": 14, "lot": "LOT-4055", "title": "Ninja Foodi 10-in-1 Air Fryer Oven", "description": "All racks and accessories included, works perfectly", "category": "Appliances", "retail_price": 249.99, "current_bid": 55.00, "my_bid": 55.00, "condition": "Good", "status": "picked_up", "pickup_status": "completed", "pickup_date": "2026-04-20", "location": "Row B, Shelf 6", "row": "B", "position": 6, "auction_end": "2026-04-18T16:00:00"},

    # Lost bids
    {"id": 15, "lot": "LOT-4100", "title": "Apple iPhone 15 Pro 256GB", "description": "Natural Titanium, minor scratches on back, Face ID works", "category": "Electronics", "retail_price": 999.00, "current_bid": 612.00, "my_bid": 450.00, "condition": "Good", "status": "lost", "pickup_status": None, "pickup_date": None, "location": "Row A, Shelf 4", "row": "A", "position": 4, "auction_end": "2026-04-22T18:00:00"},
    {"id": 16, "lot": "LOT-4205", "title": "Peloton Bike+ Stationary Bicycle", "description": "Large touchscreen, weights and shoes included, works great", "category": "Sports", "retail_price": 2495.00, "current_bid": 780.00, "my_bid": 600.00, "condition": "Good", "status": "lost", "pickup_status": None, "pickup_date": None, "location": "Row E, Shelf 1", "row": "E", "position": 1, "auction_end": "2026-04-22T20:00:00"},
    {"id": 17, "lot": "LOT-4301", "title": "Herman Miller Aeron Office Chair", "description": "Size B, PostureFit SL, minor fabric wear on armrests", "category": "Furniture", "retail_price": 1795.00, "current_bid": 445.00, "my_bid": 380.00, "condition": "Good", "status": "lost", "pickup_status": None, "pickup_date": None, "location": "Row E, Shelf 3", "row": "E", "position": 3, "auction_end": "2026-04-21T18:00:00"},
    {"id": 18, "lot": "LOT-4390", "title": "DJI Mini 3 Pro Drone", "description": "Fly More Combo, extra batteries, ND filters, carrying case", "category": "Electronics", "retail_price": 959.00, "current_bid": 388.00, "my_bid": 310.00, "condition": "Like New", "status": "lost", "pickup_status": None, "pickup_date": None, "location": "Row A, Shelf 5", "row": "A", "position": 5, "auction_end": "2026-04-21T20:00:00"},
]
